name: Run Test And Lint
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout_Repo
        uses: actions/checkout@v3
      - name: Checkout_Repo
        run: npm ci
      - name: Run_Lint
        run: npm run lint
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout_Repo
        uses: actions/checkout@v3
      - name: Checkout_Repo
        run: npm ci
      - name: Run_Test
        run: npm run test