name: Run Test And Lint
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout_Repo
        uses: actions/checkout@v3
      - name: installing packages
        run: npm ci
      - name: Run_Lint
        run: npm run lint
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout_Repo
        uses: actions/checkout@v3
      - name: installing packages
        run: npm ci
      - name: Run_Test
        run: npm run test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout_Repo
        uses: actions/checkout@v3
      - name: installing packages
        run: npm ci
      - name: Building project
        run: npm run build
      - name: deploying
        run: echo "${{ github.ref_name }}"
  Create_Pull_Request:
    runs-on: ubuntu-latest
    steps:
      - name: Create pull request using github token
      - run: |
              curl -H "Authorization: token ${{secret.JWT_TOKEN}}" -X POST -d '{
              "title": "My pull request"
              "head": "branch-name"
              "base": "master"
              "body": "Description of the changes being made"
              }' https://api.github.com/repos/SiddiquiMonis401/practice_github_workflow/pulls
