name: Run Test And Lint
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Run Lint
        run: npm run lint
  test:
    runs-on: ubuntu-latest
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Run Test
        run: npm run test