name: Create Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create pull request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'Automated pull request'
        title: 'Automated pull request'
        labels: 'automated'
        branch: ${{ env.GITHUB_HEAD_REF }}
        base: 'develop'