name: Create Dev Pull Request When a PR against master is created
on: 
  pull_request:
    types:
      - opened
    branches:
      - 'master'
jobs:
  create-dev-PR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          branch: ${{ github.head_ref }}
          base: develop 