name: Create production promotion pull request
on:
  pull_request:
    types: [opened, reopened]
    branches:
      - master
jobs:
  Create Pull Request:
    runs-on: ubuntu-latest
    steps:
      - name: Create pull request using github token
      - run: |
        curl -H "Authorization: token ${{secret.JWT_TOKEN}}" -X POST -d '{
        "title": "My pull request",
        "head": "branch-name",
        "base": "master",
        "body": "Description of the changes being made"
      }' https://api.github.com/repos/SiddiquiMonis401/practice_github_workflow/pulls 