name: Issue Workflow
on: issues
jobs:
  output_info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout_Repo
        uses: actions/checkout@v3
      - name: Printing content of issue
        run: echo "${{ toJSON(github.event.issue.title) }}"