name: Issue Workflow
on: issues
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout_Repo
        uses: actions/checkout@v3
      - name: Printing contebt
        run: echo ${{ toJSON(github) }} 